name: Deploy Vite React App to Docker Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Connect to VPS & Deploy Project
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            PROJECT_PATH="/var/www/docker/portfe"

            # Clone or pull the repo
            if [ -d "$PROJECT_PATH/.git" ]; then
              cd $PROJECT_PATH
              echo "Pulling latest changes..."
              git pull origin main
            else
              echo "Cloning project..."
              rm -rf $PROJECT_PATH
              git clone https://github.com/Ahmadfaisalkeren/portfe.git $PROJECT_PATH
            fi

      - name: Build React App
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /var/www/docker/portfe

            echo "Cleaning previous dist folder if exists..."
            [ -d dist ] && rm -rf dist

            echo "Installing dependencies..."
            sudo npm install

            echo "Building project..."
            sudo npm run build

      - name: Build & Run Docker Compose
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /var/www/docker/portfe
            docker compose up -d --build

      - name: Verify Frontend Container
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            echo "Checking frontend container..."
            docker ps | grep portfe

      - name: Reload Caddy (If Needed)
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            echo "Reloading Caddy config..."
            caddy reload --config /etc/caddy/Caddyfile
